const std = @import("std");
const builtin = @import("builtin");

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;

    try writeLandingPage(allocator, io);
    try writeComparePage(allocator, io);
    try writeApiPage(allocator, io);

    std.debug.print("Generated docs/index.html, docs/compare.html, docs/api.html\n", .{});
}

fn writeSharedCss(buf: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
    const css = "* { margin: 0; padding: 0; box-sizing: border-box; }html { scroll-behavior: smooth; }body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background: #0d1117; color: #c9d1d9; line-height: 1.6; }a { color: #e67e22; text-decoration: none; }a:hover { text-decoration: underline; }code { font-family: 'JetBrains Mono', 'Fira Code', 'SF Mono', Monaco, monospace; font-size: 0.9em; }pre { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 16px; overflow-x: auto; font-size: 0.85rem; line-height: 1.5; }pre code { background: transparent; padding: 0; font-size: inherit; }.container { max-width: 1200px; margin: 0 auto; padding: 0 24px; }.nav { background: #161b22; border-bottom: 1px solid #30363d; padding: 16px 0; position: sticky; top: 0; z-index: 100; }.nav-inner { max-width: 1200px; margin: 0 auto; padding: 0 24px; display: flex; align-items: center; justify-content: space-between; }.nav-logo { font-size: 1.4rem; font-weight: 700; color: #e67e22; }.nav-links a { color: #8b949e; margin-left: 24px; font-size: 0.95rem; font-weight: 500; }.nav-links a:hover { color: #e67e22; text-decoration: none; }.nav-links a.active { color: #e67e22; }.btn { display: inline-block; padding: 10px 20px; border-radius: 6px; font-weight: 600; font-size: 0.95rem; transition: all 0.2s; }.btn-primary { background: #e67e22; color: #0d1117; }.btn-primary:hover { background: #d35400; text-decoration: none; }.btn-secondary { background: #21262d; color: #c9d1d9; border: 1px solid #30363d; }.btn-secondary:hover { background: #30363d; text-decoration: none; }.hero { text-align: center; padding: 80px 24px 60px; }.hero h1 { font-size: 3rem; font-weight: 800; color: #e67e22; margin-bottom: 16px; }.hero p { font-size: 1.25rem; color: #8b949e; max-width: 600px; margin: 0 auto 32px; }.hero-buttons { display: flex; gap: 12px; justify-content: center; }.features { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 24px; padding: 40px 0; }.feature-card { background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 28px; transition: border-color 0.2s; }.feature-card:hover { border-color: #e67e22; }.feature-card h3 { font-size: 1.1rem; color: #e67e22; margin-bottom: 10px; }.feature-card p { color: #8b949e; font-size: 0.95rem; }.install { background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 32px; margin: 40px 0; }.install h2 { color: #e67e22; margin-bottom: 20px; }.install pre { margin: 12px 0; }.compare-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; padding: 24px 0; }.compare-col h3 { color: #e67e22; margin-bottom: 12px; font-size: 1rem; }.compare-col .lang-tag { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 600; margin-bottom: 8px; }.rust-tag { background: #b7410e22; color: #e67e22; border: 1px solid #b7410e; }.zig-tag { background: #e67e2222; color: #e67e22; border: 1px solid #e67e22; }.pattern-title { font-size: 1.2rem; font-weight: 600; color: #e67e22; margin: 32px 0 16px; padding-bottom: 8px; border-bottom: 1px solid #30363d; }.api-module { background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 24px; margin: 20px 0; }.api-module h3 { color: #e67e22; font-size: 1.1rem; margin-bottom: 16px; }.api-decl { padding: 10px 14px; border-left: 3px solid #e67e22; margin: 8px 0; background: #0d1117; border-radius: 0 6px 6px 0; }.api-decl code { color: #d2a8ff; }.api-doc { color: #8b949e; font-style: italic; margin-top: 4px; font-size: 0.9rem; }footer { text-align: center; padding: 40px 24px; color: #8b949e; font-size: 0.9rem; border-top: 1px solid #30363d; margin-top: 60px; }@media (max-width: 768px) { .compare-grid { grid-template-columns: 1fr; } .hero h1 { font-size: 2rem; } .hero-buttons { flex-direction: column; align-items: center; } }";
    try buf.appendSlice(allocator, css);
}

fn pageHead(buf: *std.ArrayList(u8), allocator: std.mem.Allocator, title: []const u8, active: []const u8) !void {
    try buf.appendSlice(allocator,
        \\<!DOCTYPE html>
        \\<!-- This file is auto-generated by docs/generate.zig -->
        \\<!-- Do not edit manually -->
        \\<!-- Run `zig build docs` to regenerate -->
        \\<!--
        \\  Architecture:
        \\  - docs/index.html   : Landing page (hero, install, features)
        \\  - docs/compare.html : Rust ↔ zust side-by-side comparison
        \\  - docs/api.html     : API reference (auto-generated from lib/*.zig)
        \\  -->
        \\<!--
        \\  Design document: docs/plans/2026-05-16-docs-redesign-design.md
        \\  -->
        \\<!--
        \\  Deployment: GitHub Actions workflow .github/workflows/docs.yml
        \\  runs `zig build docs` on every push to main and deploys to Pages.
        \\  -->
        \\<!--
        \\  Local preview: zig build docs && open docs/index.html
        \\  -->
        \\<html lang="en">
        \\<head>
        \\  <meta charset="UTF-8">
        \\  <meta name="viewport" content="width=device-width, initial-scale=1.0">
        \\  <title>
    );
    try buf.appendSlice(allocator, title);
    try buf.appendSlice(allocator,
        \\</title>
        \\  <style>
    );
    try writeSharedCss(buf, allocator);
    try buf.appendSlice(allocator,
        \\  </style>
        \\</head>
        \\<body>
        \\  <nav class="nav">
        \\    <div class="nav-inner">
        \\      <a href="index.html" class="nav-logo">zust</a>
        \\      <div class="nav-links">
    );

    const links = [_]struct { name: []const u8, href: []const u8 }{
        .{ .name = "Home", .href = "index.html" },
        .{ .name = "Rust → zust", .href = "compare.html" },
        .{ .name = "API", .href = "api.html" },
        .{ .name = "GitHub", .href = "https://github.com/e-jerk/zust" },
    };

    for (links) |link| {
        const cls = if (std.mem.eql(u8, link.name, active)) " class=\"active\"" else "";
        try buf.appendSlice(allocator, "        <a href=\"");
        try buf.appendSlice(allocator, link.href);
        try buf.appendSlice(allocator, "\"");
        try buf.appendSlice(allocator, cls);
        try buf.appendSlice(allocator, ">");
        try buf.appendSlice(allocator, link.name);
        try buf.appendSlice(allocator, "</a>\n");
    }

    try buf.appendSlice(allocator,
        \\      </div>
        \\    </div>
        \\  </nav>
        \\  <div class="container">
    );
}

fn pageFoot(buf: *std.ArrayList(u8), allocator: std.mem.Allocator) !void {
    try buf.appendSlice(allocator,
        \\  </div>
        \\  <footer>
        \\    <p>zust — Zero-cost ownership for Zig</p>
        \\    <p style="margin-top:8px;">
        \\      <a href="index.html">Home</a> ·
        \\      <a href="compare.html">Comparison</a> ·
        \\      <a href="api.html">API</a> ·
        \\      <a href="https://github.com/e-jerk/zust">GitHub</a>
        \\    </p>
        \\  </footer>
        \\</body>
        \\</html>
    );
}

fn writeFile(path: []const u8, data: []const u8, io: std.Io) !void {
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = path, .data = data });
}

// ─── Landing Page ───

fn writeLandingPage(allocator: std.mem.Allocator, io: std.Io) !void {
    var buf = std.ArrayList(u8).empty;
    defer buf.deinit(allocator);

    try pageHead(&buf, allocator, "zust — Zero-Cost Ownership for Zig", "Home");

    try buf.appendSlice(allocator,
        \\  <div class="hero">
        \\    <h1>zust</h1>
        \\    <p>Zero-cost memory safety for Zig via comptime typestate.<br>
        \\       Rust-inspired ownership without runtime overhead.</p>
        \\    <div class="hero-buttons">
        \\      <a href="compare.html" class="btn btn-primary">See Rust → zust Comparison</a>
        \\      <a href="https://github.com/e-jerk/zust" class="btn btn-secondary">GitHub</a>
        \\    </div>
        \\  </div>
        \\  <div class="features">
        \\    <div class="feature-card">
        \\      <h3>🛡️ Compile-Time Ownership</h3>
        \\      <p>Every ownership transfer is visible in the type system. Double-free and use-after-free are caught at compile time via <code>@compileError</code>.</p>
        \\    </div>
        \\    <div class="feature-card">
        \\      <h3>⚡ SIMD Acceleration</h3>
        \\      <p>16 primitives with 16-byte + 32-byte vector paths. String search, array operations, and bit manipulation are up to 22× faster than scalar.</p>
        \\    </div>
        \\    <div class="feature-card">
        \\      <h3>🔍 Static Analyzer</h3>
        \\      <p>30 bug class detections including data races, null dereferences, buffer overflows, and cross-function contract violations. Auto-fix generation included.</p>
        \\    </div>
        \\    <div class="feature-card">
        \\      <h3>🔌 LSP Server</h3>
        \\      <p>JSON-RPC 2.0 LSP with diagnostics, completion, go-to-definition, hover docs, workspace symbol search, and find-references.</p>
        \\    </div>
        \\    <div class="feature-card">
        \\      <h3>🔄 Safe Mode Transpiler</h3>
        \\      <p>Convert unsafe Zig to zust-safe Zig via AST rewriting. 20 patterns covering the most common unsafe idioms.</p>
        \\    </div>
        \\    <div class="feature-card">
        \\      <h3>🌐 Cross-Platform</h3>
        \\      <p>Native on macOS, Linux, Windows. WebAssembly build for browser IDEs. Cross-compiles to 5 targets.</p>
        \\    </div>
        \\  </div>
        \\  <div class="install">
        \\    <h2>Installation</h2>
        \\    <p>Add to your <code>build.zig</code>:</p>
        \\    <pre><code>const safe_module = b.addModule("safe", .{
        \\    .root_source_file = b.path("lib/safe.zig"),
        \\});</code></pre>
        \\    <p>Then import in your code:</p>
        \\    <pre><code>const safe = @import("safe");
        \\var list = safe.ArrayList(i32).init(allocator);
        \\defer list.deinit(allocator);</code></pre>
        \\    <p>Or use the <a href="https://github.com/e-jerk/zust">adoption scripts</a> for one-command migration.</p>
        \\  </div>
    );

    try pageFoot(&buf, allocator);
    try writeFile("docs/index.html", buf.items, io);
}

// ─── Comparison Page ───

const Comparison = struct {
    title: []const u8,
    rust: []const u8,
    zust: []const u8,
};

const comparisons = [_]Comparison{
    .{
        .title = "Heap Allocation",
        .rust =
            \\use std::boxed::Box;
            \\fn main() {
            \\    let b = Box::new(42);
            \\    println!("{}", b);
            \\} // dropped automatically
        ,
        .zust =
            \\const safe = @import("safe");
            \\fn foo(allocator: std.mem.Allocator) !void {
            \\    var b = try safe.Box(i32, 0, 0, 0).init(allocator, 42);
            \\    std.debug.print("{d}", .{b.ptr.*});
            \\    _ = b.deinit(); // type error if forgotten
            \\}
        ,
    },
    .{
        .title = "Growable Array",
        .rust =
            \\let mut vec = Vec::new();
            \\vec.push(1);
            \\vec.push(2);
            \\let x = vec.pop(); // Option<i32>
        ,
        .zust =
            \\var list = safe.ArrayList(i32).init(allocator);
            \\defer list.deinit(allocator);
            \\try list.append(allocator, 1);
            \\try list.append(allocator, 2);
            \\const x = list.pop(); // i32 (panic if empty)
        ,
    },
    .{
        .title = "Hash Map",
        .rust =
            \\use std::collections::HashMap;
            \\let mut map = HashMap::new();
            \\map.insert("key", 42);
            \\let val = map.get("key");
        ,
        .zust =
            \\var map = safe.HashMap(safe.String, i32).init(allocator);
            \\defer map.deinit(allocator);
            \\try map.put(allocator, "key", 42);
            \\const val = map.get("key"); // ?i32
        ,
    },
    .{
        .title = "Shared Ownership",
        .rust =
            \\use std::sync::Arc;
            \\let a = Arc::new(42);
            \\let b = Arc::clone(&a);
            \\println!("{}", Arc::strong_count(&a));
        ,
        .zust =
            \\var a = try safe.Arc(i32).init(allocator, 42);
            \\defer a.deinit();
            \\var b = a.clone();
            \\std.debug.print("{d}", .{a.strong_count()});
        ,
    },
    .{
        .title = "Mutex",
        .rust =
            \\use std::sync::Mutex;
            \\let m = Mutex::new(0);
            \\{
            \\    let mut guard = m.lock().unwrap();
            \\    *guard += 1;
            \\} // unlocked automatically
        ,
        .zust =
            \\var m = safe.Mutex(i32).init(0);
            \\defer m.deinit();
            \\{
            \\    var guard = m.lock();
            \\    guard.ptr.* += 1;
            \\    guard.deinit(); // required in Zig
            \\}
        ,
    },
    .{
        .title = "String",
        .rust =
            \\let mut s = String::new();
            \\s.push_str("hello");
            \\s.push_str(" world");
            \\println!("{}", s);
        ,
        .zust =
            \\var s = safe.String.init(allocator);
            \\defer s.deinit(allocator);
            \\try s.appendSlice("hello");
            \\try s.appendSlice(" world");
            \\std.debug.print("{s}", .{s.slice()});
        ,
    },
    .{
        .title = "Optional / Null",
        .rust =
            \\let x: Option<i32> = Some(42);
            \\let y = x.unwrap(); // panics if None
            \\let z = x.unwrap_or(0);
        ,
        .zust =
            \\const x: ?i32 = 42;
            \\const y = x.?; // compile error if null path untaken
            \\const z = x orelse 0;
        ,
    },
    .{
        .title = "Iterator",
        .rust =
            \\let v = vec![1, 2, 3];
            \\let doubled: Vec<i32> = v.iter()
            \\    .map(|x| x * 2)
            \\    .collect();
        ,
        .zust =
            \\var v = safe.ArrayList(i32).init(allocator);
            \\// ... populate ...
            \\var iter = safe.SliceIter(i32).init(v.slice());
            \\var doubled = try iter.map(allocator, struct {
            \\    fn f(x: i32) i32 { return x * 2; }
            \\}.f);
        ,
    },
};

fn writeComparePage(allocator: std.mem.Allocator, io: std.Io) !void {
    var buf = std.ArrayList(u8).empty;
    defer buf.deinit(allocator);

    try pageHead(&buf, allocator, "Rust → zust Comparison", "Rust → zust");

    try buf.appendSlice(allocator,
        \\  <div class="hero">
        \\    <h1 style="font-size:2rem;">Rust → zust</h1>
        \\    <p>Side-by-side comparison of common ownership patterns.<br>
        \\       Coming from Rust? Here's how zust maps to what you know.</p>
        \\  </div>
    );

    for (comparisons) |cmp| {
        try buf.appendSlice(allocator, "  <div class=\"pattern-title\">");
        try buf.appendSlice(allocator, cmp.title);
        try buf.appendSlice(allocator, "</div>\n");

        try buf.appendSlice(allocator,
            \\  <div class="compare-grid">
            \\    <div class="compare-col">
            \\      <div class="lang-tag rust-tag">RUST</div>
            \\      <pre><code>
        );
        try buf.appendSlice(allocator, cmp.rust);
        try buf.appendSlice(allocator,
            \\</code></pre>
            \\    </div>
            \\    <div class="compare-col">
            \\      <div class="lang-tag zig-tag">ZUST</div>
            \\      <pre><code>
        );
        try buf.appendSlice(allocator, cmp.zust);
        try buf.appendSlice(allocator,
            \\</code></pre>
            \\    </div>
            \\  </div>
        );
    }

    try pageFoot(&buf, allocator);
    try writeFile("docs/compare.html", buf.items, io);
}

// ─── API Page ───

fn writeApiPage(allocator: std.mem.Allocator, io: std.Io) !void {
    var buf = std.ArrayList(u8).empty;
    defer buf.deinit(allocator);

    try pageHead(&buf, allocator, "zust API Reference", "API");

    try buf.appendSlice(allocator,
        \\  <div class="hero">
        \\    <h1 style="font-size:2rem;">API Reference</h1>
        \\    <p>58 modules · 148 public declarations</p>
        \\  </div>
    );

    var file_count: usize = 0;
    var decl_count: usize = 0;

    var dir = try std.Io.Dir.cwd().openDir(io, "lib", .{ .iterate = true });
    defer dir.close(io);

    var it = dir.iterate();
    while (try it.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".zig")) continue;
        if (std.mem.eql(u8, entry.name, "safe.zig")) continue;

        file_count += 1;
        const file_path = try std.fmt.allocPrint(allocator, "lib/{s}", .{entry.name});
        defer allocator.free(file_path);

        const source = try std.Io.Dir.cwd().readFileAlloc(io, file_path, allocator, .limited(1 << 20));
        defer allocator.free(source);
        const source_z = try allocator.dupeZ(u8, source);
        defer allocator.free(source_z);

        var ast = try std.zig.Ast.parse(allocator, source_z, .zig);
        defer ast.deinit(allocator);

        if (ast.errors.len > 0) continue;

        const module_name = entry.name[0 .. entry.name.len - 4];
        try buf.appendSlice(allocator, "  <div class=\"api-module\">\n");
        try buf.appendSlice(allocator, "    <h3>");
        try buf.appendSlice(allocator, module_name);
        try buf.appendSlice(allocator, "</h3>\n");

        const decls = ast.rootDecls();
        for (decls) |decl| {
            const tag = ast.nodes.items(.tag)[@intFromEnum(decl)];
            const main_token = ast.nodes.items(.main_token)[@intFromEnum(decl)];

            var docs_text: []const u8 = "";
            const doc_start = ast.nodes.items(.main_token)[@intFromEnum(decl)];
            for (0..5) |offset| {
                if (doc_start < offset) break;
                const tok_idx = doc_start - offset;
                const tok_tag = ast.tokens.items(.tag)[tok_idx];
                if (tok_tag == .doc_comment) {
                    docs_text = ast.tokenSlice(@intCast(tok_idx));
                }
            }

            switch (tag) {
                .simple_var_decl, .local_var_decl, .global_var_decl, .aligned_var_decl => {
                    const decl_name = ast.tokenSlice(main_token + 1);
                    const is_pub = isPublic(ast, main_token);
                    if (is_pub) {
                        decl_count += 1;
                        try buf.appendSlice(allocator, "    <div class=\"api-decl\">\n      <code>pub const ");
                        try buf.appendSlice(allocator, decl_name);
                        try buf.appendSlice(allocator, "</code>\n");
                        if (docs_text.len > 0) {
                            try buf.appendSlice(allocator, "      <div class=\"api-doc\">");
                            try buf.appendSlice(allocator, docs_text);
                            try buf.appendSlice(allocator, "</div>\n");
                        }
                        try buf.appendSlice(allocator, "    </div>\n");
                    }
                },
                .fn_decl => {
                    var buf_node: [1]std.zig.Ast.Node.Index = undefined;
                    if (ast.fullFnProto(&buf_node, ast.nodes.items(.data)[@intFromEnum(decl)].node_and_node[0])) |proto| {
                        if (proto.name_token) |nt| {
                            const fn_name = ast.tokenSlice(nt);
                            const is_pub = isPublic(ast, ast.nodes.items(.main_token)[@intFromEnum(decl)]);
                            if (is_pub) {
                                decl_count += 1;
                                try buf.appendSlice(allocator, "    <div class=\"api-decl\">\n      <code>pub fn ");
                                try buf.appendSlice(allocator, fn_name);
                                try buf.appendSlice(allocator, "()</code>\n");
                                if (docs_text.len > 0) {
                                    try buf.appendSlice(allocator, "      <div class=\"api-doc\">");
                                    try buf.appendSlice(allocator, docs_text);
                                    try buf.appendSlice(allocator, "</div>\n");
                                }
                                try buf.appendSlice(allocator, "    </div>\n");
                            }
                        }
                    }
                },
                else => {},
            }
        }

        try buf.appendSlice(allocator, "  </div>\n");
    }

    try buf.appendSlice(allocator, "  <p style=\"text-align:center; color:#8b949e; margin-top:20px;\">");
    var stats_buf: [64]u8 = undefined;
    const stats = try std.fmt.bufPrint(&stats_buf, "{d} modules · {d} declarations", .{ file_count, decl_count });
    try buf.appendSlice(allocator, stats);
    try buf.appendSlice(allocator, "</p>\n");

    try pageFoot(&buf, allocator);
    try writeFile("docs/api.html", buf.items, io);
}

fn isPublic(ast: std.zig.Ast, main_token: u32) bool {
    if (main_token == 0) return false;
    const prev_tag = ast.tokens.items(.tag)[main_token - 1];
    return prev_tag == .keyword_pub;
}
